### ISSUE TITLE
Bookmarklet

### ISSUE THREAD

**Issue by donuts-are-good** [devidw/replika-export#3]
Was this a bookmarklet at some point? I have this stored, and it references this repo, but I'm not sure if it still works because the file it references is gone. 

```
javascript:(function(){     const script = document.createElement('script');     script.setAttribute('src', 'https://cdn.jsdelivr.net/gh/devidw/replika-export/index.js');     document.body.appendChild(script); }())

```

**Comment by devidw** [comment]
Yes, but the bookmarklet solution was kind of inefficient and slow because it could only go in the speed of a simulated user scrolling.

So, instead, I have rewritten this into a script that is able to directly communicate with the Replika API servers via web sockets. Please follow the readme for an instruction on how to use it, or kindly raise an issue if something is not working as expected.

If you are still interested in the bookmarklet solution, you can find it in the commit history.

Here is the repo source before changing the approach: https://github.com/devidw/replika-chat-export/tree/aa0da92227866bcc94f12df43d669be7c82416e6

And here is the bookmarklet file, if you still want to use it, you can use this link, or better a GIT CDN solution like jsdelivr and replace the script source in the code snippet: https://github.com/devidw/replika-chat-export/blob/aa0da92227866bcc94f12df43d669be7c82416e6/index.js
