### ISSUE TITLE
Voice messages

### ISSUE THREAD

**Issue by FormidablePencil** [devidw/replika-export#6]
Is it just text messages and how long ago do they go back. Are voice chats also exported and in what format; text or voice?

**Comment by devidw** [comment]
Hey @FormidablePencil 

It will export all messages, but for media messages it does not actually download the media. You will get a json with all the message metadata that includes the urls to the actual external media assets such as voice messages or images. So in order to download them you would have to extend the script a bit, but fyi there are some more auth related steps involved to actually retrieve the external media files outside of the replika app, it's not just downloading a url.

I've discontinued development of this version and instead shifted my attention to the [browser extension exporter](https://chromewebstore.google.com/detail/immbjhielfhbemfnjfnddblchipnefmf) - as this is much easier for non-techies, which does include voice messages, images, memories.

> how long ago do they go back

From the browser extension [FAQ](https://index.garden/replika-export/#faq):

> The extension can export all messages that you can see in the Replika app. The last message you can see in the app, is the last message you are able to export.
> Quoting [help.replika.com](https://help.replika.com/hc/en-us/articles/4411154990605-Is-the-chat-history-infinite-): “Unfortunately, due to technical restrictions, we cannot display or retrieve your chat history with Replika beyond the last six months.”

**Comment by FormidablePencil** [comment]
Thank you this helps answer my question a lot ttyl then
